"""empty message

Revision ID: 730bcf66a000
Revises: 20c9eb45218e
Create Date: 2021-04-07 03:00:48.328631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '730bcf66a000'
down_revision = '20c9eb45218e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('films',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=28), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('films')
    # ### end Alembic commands ###
